stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw
    params:
    - data_preprocessing.test_size
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - src/features/feature_engineering.py
    - data/interim
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - src/model/model_building.py
    - data/interim
    params:
    - model.C
    - model.solver
    - model.penalty
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - src/model/model_evaluation.py
    - models/model.pkl
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json
  
  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - src/model/register_model.py
    - reports/experiment_info.json

