apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: creditcard-fraud
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      annotations:
        # Important: Prometheus Operator often looks for these annotations
        # on pods/services if not explicitly specified in ServiceMonitor
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: flask-app
          image: rnjt80/creditcard_fraud:5bd2f0b4710c77dc6901829f4b50b94cbeac4dd7
          ports:
            - name: web
              containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: DAGSHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dagshubtoken
                  key: DAGSHUB_TOKEN
      imagePullSecrets:
        - name: dockerhub-creds
