apiVersion: v1
kind: Secret # use ExternalSecret for production use as its good practice to store secretes in cloud's native secret manager
metadata:
  namespace: creditcard_fraud
  name: DagsHubToken
  data:
    dagshub_token: ${{secrets.DAGSHUB_TOKEN}} # this for testing only, for production you should use the secrte stored in the secrete manager
    