name: Credit card fraud detection app CICD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: '${{vars.DOCKERHUB_USER}}/credicard_fraud'

jobs:
  DataPipeLine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: Run Pipeline
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          dvc repro

      - name: Run model test
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to Production
        env:
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          python scripts/promot_model.py

      - name: Run flask app test
        env: 
          DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          python -m unittest tests/test_flask_app.py

      # - name: Extract Docker image metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ vars.DOCKERHUB_USER }}/creditcard_fraud

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG = "sha-${{ github.sha }}" #Use github sha for unique tag
          echo "Bulding Image: ${IMAGE_NAME}:${IMAGE_TAG}"
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          

